// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kfkfukpfhhcynyqpnwpp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtma2Z1a3BmaGhjeW55cXBud3BwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2NDY0MDIsImV4cCI6MjA1ODIyMjQwMn0.sMRo69h7e57wl9D3mC7xnnzNrRY-RgfWYaaX6cn7dBs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);